import {
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Download,
  Filter,
  GraduationCap,
  Loader2,
  LogIn,
  type Icon as LucideIcon,
  Moon,
  PauseCircle,
  Play,
  RotateCcw,
  Save,
  SlidersHorizontal,
  StopCircle,
  Sun,
  TimerReset,
  User,
  X,
  XCircle,
} from "lucide-react";

export type Icon = LucideIcon;
export const Icons = {
  Logo: GraduationCap,
  Login: LogIn,
  play: Play,
  pause: PauseCircle,
  chrono: TimerReset,
  newSession: RotateCcw,
  save: Save,
  stop: StopCircle,
  close: XCircle,
  CloseCross: X,
  copy: Clipboard,
  loading: Loader2,
  User: User,
  sun: Sun,
  moon: Moon,
  filter: Filter,
  filter2: SlidersHorizontal,
  download: Download,
  Calendar: CalendarClock,
  check: Check,
  arrowLeft: ChevronLeft,
  arrowRight: ChevronRight,
};
